pr_pipeline:
  only:
  - /^github\/pr[\d]+_.*$/
  variables:
    SPACK_PR_BRANCH: ${CI_COMMIT_REF_NAME}
    SPACK_IS_PR_PIPELINE: "True"
  trigger:
    project: scott/test-downstream
    strategy: depend

merge_pipeline:
  only:
  - master
  variables:
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    SPACK_SIGNING_KEY: ${SPACK_SIGNING_KEY}
  trigger:
    project: scott/test-downstream
    strategy: depend
